# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-31 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_auto_20180331_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='expert',
            name='user',
        ),
        migrations.DeleteModel(
            name='Expert',
        ),
    ]
