# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-31 09:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expert', '0003_auto_20180331_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Automotive', 'Automotive'), ('Business', 'Business'), ('Career', 'Career'), ('Education', 'Education'), ('Finance', 'Finance'), ('Fitness', 'Fitness'), ('Health', 'Health'), ('Legal', 'Legal'), ('Lifestyle', 'Lifestyle'), ('RealEstate', 'RealEstate'), ('Spiritual', 'Spiritual'), ('Tax and Accounting', 'Tax and Accounting'), ('Technology', 'Technology'), ('Travels', 'Travels')], max_length=50)),
                ('profession', models.CharField(choices=[('Doctor', 'Doctor'), ('Engineer', 'Engineer'), ('Lawyer', 'Lawyer'), ('MBA', 'MBA'), ('Professor', 'Professor'), ('Businessman', 'Businessman'), ('Athlete', 'Athlete'), ('Actor', 'Actor'), ('Consultant', 'Consultant'), ('Spiritualist', 'Spiritualist'), ('others', 'others')], max_length=50)),
                ('joined_date', models.DateTimeField(auto_now=True)),
                ('approved_expert', models.BooleanField(default=False)),
                ('mme_id', models.CharField(default='00000000', max_length=10)),
                ('profile_name', models.CharField(max_length=50)),
                ('achievements', models.CharField(max_length=100)),
                ('linkedin_Profile', models.URLField()),
                ('appointment_fee', models.IntegerField()),
                ('about', models.TextField(null=True)),
                ('address', models.CharField(max_length=100)),
                ('emailid', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='expert.Expert')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
