# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-31 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0004_auto_20180331_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='department',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Automotive', 'Automotive'), ('Business', 'Business'), ('Career', 'Career'), ('Education', 'Education'), ('Finance', 'Finance'), ('Fitness', 'Fitness'), ('Health', 'Health'), ('Legal', 'Legal'), ('Lifestyle', 'Lifestyle'), ('RealEstate', 'RealEstate'), ('Spiritual', 'Spiritual'), ('Tax and Accounting', 'Tax and Accounting'), ('Technology', 'Technology'), ('Travels', 'Travels'), ('others', 'others')], max_length=50),
        ),
    ]
