# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-31 09:38
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0005_auto_20180331_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='profile_pic',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
