# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-31 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0006_expert_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expert',
            options={'ordering': ['-joined_date']},
        ),
    ]
