# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-31 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0007_auto_20180331_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
