# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-31 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0009_auto_20180331_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expert',
            options={'ordering': ['appointment_fee']},
        ),
    ]
