# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-29 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='cc_myself',
        ),
    ]
