# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-01 05:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAndLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='anonymous', max_length=30)),
                ('comment_title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('commented_date', models.DateTimeField(auto_now=True)),
                ('like_post', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Automotive', 'Automotive'), ('Business', 'Business'), ('Career', 'Career'), ('Education', 'Education'), ('Finance', 'Finance'), ('Fitness', 'Fitness'), ('Health', 'Health'), ('Legal', 'Legal'), ('Lifestyle', 'Lifestyle'), ('RealEstate', 'RealEstate'), ('Spiritual', 'Spiritual'), ('Tax and Accounting', 'Tax and Accounting'), ('Technology', 'Technology'), ('Travels', 'Travels'), ('others', 'others')], max_length=50)),
                ('post_title', models.CharField(max_length=50)),
                ('post_pic', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='post_pics/')),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('summary', models.CharField(max_length=100)),
                ('content', models.TextField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['published_date'],
            },
        ),
        migrations.AddField(
            model_name='commentandlikes',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_and_likes', to='blog.Post'),
        ),
    ]
