# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-01 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180401_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(max_length=400),
        ),
    ]
